### ISSUE TITLE
为什么iOS 集成GT后，发现GT会偷偷发送数据至这个IP：183.232.93.173

### ISSUE THREAD

**Issue by Mark1984** [Tencent/GT#18]
![an](https://cloud.githubusercontent.com/assets/15794127/23930529/e3a3ed04-0967-11e7-8f50-c8d2c947c12f.png)

**Comment by r551** [comment]
GT默认集成了统计crash的bugly和运营统计的mta，在编译源码的时候可以很容易的去除掉。
