### ISSUE TITLE
【适配问题】AUT界面选择调试应用，勾选PSS和CPU后，出参界面无法显示出PSS和CPU值

### ISSUE THREAD

**Issue by yesxingxing** [Tencent/GT#20]
AUT界面选择调试应用，勾选PSS和CPU后并且点击Lanuch启动应用，在出参界面无法显示出该应用的PSS和CPU值
【备注】使用公司5.1、6.0、7.0的机型都试过，不适配

**Comment by nijian81** [comment]
我也遇到这个问题，可能无解。。。

**Comment by gdky005** [comment]
我再 7.1 Nexus 6P 上是可以的，进入 app 页面后，点击哪个  refresh  才能自动出来。

**Comment by svengong** [comment]
由于android版本的更新，sh命令只能获取当前进程的数据，其他进程的信息已经无法获取。上门有人说6p可以，可能是因为root过了。
现在可以试一下3.1版本

**Comment by gdky005** [comment]
确实的 root 了哈。
