### ISSUE TITLE
GT能否获取RSS内存数据?

### ISSUE THREAD

**Issue by RealLau** [Tencent/GT#21]
伟大的GT团队，你们好!
        目前内存方面，应该是获取的PSS数据；能否支持配置增加对RSS的获取和展示呢? 包括指定某个APP对CPU的占用，而不是CPU整体被全部消耗了多少?  O(∩_∩)O谢谢

**Comment by r551** [comment]
可以，gt.qq.com里有个quickstart文档，请参考一下。
