### ISSUE TITLE
流畅度检测一直是 NOT　OK

### ISSUE THREAD

**Issue by tyouter** [Tencent/GT#23]
进入“流畅度调试”界面，点击检测，左上角显示　“NOT　OK”。
按照提示，点击更改－＞点击重启。
点击检测，左上角仍然为　“NOT　OK”。
重启平板，进入GT，流畅度调试界面，点击检测，左上角显示　“NOT　OK”。

**Comment by xiaosongluo** [comment]
说明gt获取root权限获取不成功

**Comment by svengong** [comment]
更新了，试一下3.1
