### ISSUE TITLE
流畅度测试

### ISSUE THREAD

**Issue by CCGCHEN** [Tencent/GT#27]
感觉流畅度测试的工具好像不太准，一直都是60，在明显有卡顿的地方也是。只有在界面切换的时候才显示其他数值

**Comment by r551** [comment]
确实是，目前的方案对Android6.0以上的大部分机型都不适配了

**Comment by svengong** [comment]
试一下3.1吧

**Comment by leon19920617** [comment]
3.1怎么下，最新的都是2.2
