### ISSUE TITLE
Android Studio Support？

### ISSUE THREAD

**Issue by xuyisheng** [Tencent/GT#3]

**Comment by r551** [comment]
暂不支持的，工程比较简单，可以拷了源码自己写gradle

**Comment by lonelysnow** [comment]
如果不会写gradle，从Eclipse里右键点工程选Export，然后选择Android--Generate Gradle Build Files，生成build.gradle 。然后从Android Studio里点导入，导入的时候注意只选这个build.gradle。
导入其他还有一些细节根据个人环境差别等原因不怎么好具体描述，自己多试几次就好了。

**Comment by 8enet** [comment]
https://github.com/8enet/GT/tree/master/android  
添加了gradle和所有依赖 jar，自己打包就可以不 root 查看流畅度了:smile:

**Comment by elmapa** [comment]
https://github.com/8enet/GT/tree/master/android

**Comment by svengong** [comment]
已经支持最新的Android studio了
