### ISSUE TITLE
应用内读取proc/stat，在android8没有权限

### ISSUE THREAD

**Issue by Guiqifeitian** [Tencent/GT#39]
您好，应用内读取proc/stat，在android8没有权限，我使用processbuilder执行system/bin/cat /proc/stat也读取不到内容，请问有什么方法能够解决？

**Comment by brianxcli** [comment]
某一个8.0的版本底层设置了权限，应用程序无法读取这个文件了。目前看来无解。

**Comment by testerclub** [comment]
能否通过其他方式获取CPU数据，不读取proc/stat
