### ISSUE TITLE
GT 2.2.5.5 no Responding after root on Flyme OS 4.5.0.4Q

### ISSUE THREAD

**Issue by atom992** [Tencent/GT#4]
I am using M571C with Flyme OS 4.5.0.4Q base on  Android 5.1.
and [GT 2.2.5.5](http://gt.qq.com/download/a/GT_2.2.5.5.apk).
When I am not root my device, all things works fine. 
but after I root my device, And I allow the GT, GT is no responding.
When I disallow the GT,
The notification shows Version:Release 2.2 GT is running.
The GT is crash.

本机环境：
魅族 魅蓝Note2 电信版（机器型号：M571C） 操作系统：Flyme OS 4.5.0.4Q(基于Android5.1)
使用GT2.2.5.5
问题描述：
在未root手机之前，使用GT基本功能正常；
在root手机之后（并允许GT），GT启动后无响应；
在root手机之后（并禁止GT），GT启动后无响应，通知栏显示：Version:Release 2.2 GT is running；

**Comment by tjzhaomengyi** [comment]
师傅，咱们可以说中文么

**Comment by r551** [comment]
最近入手了新的魅族，有空会查一下在新版本上有没有问题

**Comment by atom992** [comment]
可以正常工作了，谢谢！
