### ISSUE TITLE
Android O Permission denied

### ISSUE THREAD

**Issue by coolegos** [Tencent/GT#42]
![image](https://user-images.githubusercontent.com/6348861/41213595-de8a04e0-6d78-11e8-94e2-1c90ad568ef7.png)
在部分Android O 上(oppo R15)获取不都CPU 的数据。

**Comment by yxcSini** [comment]
@coolegos android o以上都获取不到吧 权限限制了proc

**Comment by coolegos** [comment]
在某些Android O 上还是可以拿到

**Comment by ukyo6** [comment]
@coolegos 请问你解决了吗,有什么方案吗
