### ISSUE TITLE
Error occurred while communicating with CMake server

### ISSUE THREAD

**Issue by nicainci** [Tencent/GT#63]
[== "CMake Server" ==[

{"supportedProtocolVersions":[{"isExperimental":true,"major":1,"minor":1}],"type":"hello"}

]== "CMake Server" ==]

**Comment by nicainci** [comment]
有人遇到这样的情况吗？

**Comment by nicainci** [comment]
NDK配置问题

**Comment by shengguan** [comment]
什么配置问题  我也遇到这个情况了

**Comment by nicainci** [comment]
我下载安装最新的NDK，然后gradle版本改成3.2.0就可以了

**Comment by shengguan** [comment]
改了gradle版本好了  谢谢了

**Comment by bapuqln** [comment]
改了还是不行

**Comment by wintonBy** [comment]
不要用3.0.1这个gradle版本

**Comment by zhuff-hb** [comment]
gradle版本和gradle插件版本要注意一对一对出现
